AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'scrap/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ExtraSpacing:
  AllowForAlignment: false
  AllowBeforeTrailingComments: true
  ForceEqualSignAlignment: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/LineLength:
  Max: 260

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 250
  Exclude:
    - config/**/*
    - db/migrate/*
    - test/**/*
    - spec/**/*

Metrics/ClassLength:
  Max: 800
  Exclude:
    - test/**/*
    - spec/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 75
  Exclude:
    - test/**/*
    - spec/**/*

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - cc
    - db
    - id
    - if
    - in
    - io
    - ip
    - is
    - of
    - "on"
    - os
    - pp
    - rr
    - to

Naming/PredicatePrefix:
  ForbiddenPrefixes: []

Naming/VariableNumber:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FetchEnvVar:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/YodaExpression:
  Enabled: false

Security/Eval:
  Enabled: false
